ACCESSIONS, = glob_wildcards("DATA/{accession}_1.fastq.gz")
rule all:
    input:
        expand("RESULTS/{accession}_ARGs_90.mapstat", accession=ACCESSIONS),
        expand("RESULTS/{accession}_ARGs_80.mapstat", accession=ACCESSIONS)

rule kma:
    input:
        "DATA/{accession}_1.fastq.gz"
    output:
        "RESULTS/{accession}_ARGs_90.mapstat"
    params:
        ref="/DATABASES/resfinder_db/all.fsa"
    resources:
        mem_mb=200,
        tmpdir="./tmp"
    shell:
        """
        /kma/kma -i {input} -o RESULTS/{wildcards.accession}_ARGs_90 -t_db {params.ref} -nc -na -nf -ef -ID 90 -ml 60
        """
rule kma_80:
    input:
       "DATA/{accession}_1.fastq.gz"
    output:
        "RESULTS/{accession}_ARGs_80.mapstat"
    params:
        ref="/DATABASES/resfinder_db/all.fsa"
    resources:
        mem_mb=200,
        tmpdir="./tmp"
    shell:
       """
       /kma/kma -i {input} -o RESULTS/{wildcards.accession}_ARGs_80 -t_db {params.ref} -nc -na -nf -ef -1t1 -nc -na -nf -ef -ID 80 -ml 60
       """
